services:
  termix:
    image: ghcr.io/lukegus/termix:release-2.3.2
    container_name: termix
    restart: unless-stopped
    ports:
      - '127.0.0.1:8748:8080'
    volumes:
      - ./termix-data:/app/data
    env_file:
      - .env
    environment:
      PORT: '8080'
      GUACD_URL: 'tcp://guacd:4822'
      OIDC_FORCE_HTTPS: 'true'
      OIDC_ALLOW_REGISTRATION: 'false'
      ALLOW_REGISTRATION: 'false'
      LOG_LEVEL: 'info'
    depends_on:
      - guacd
    networks:
      - termix-net

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    networks:
      - termix-net

networks:
  termix-net:
    driver: bridge