#!/bin/bash
# RSS Scan Script for Pattern B (n8n pipeline)
# Reads the RSS XML feed generated by the n8n "RSS Curation par Hermes" workflow,
# compares with seen-links file, outputs new articles between markers for agent filtering.
#
# Place at ~/.hermes/scripts/rss-n8n-scan.sh and reference by bare filename in cron.

SEEN_FILE="$HOME/.hermes/rss-seen.txt"
RSS_URL="http://localhost:5678/webhook/rss-curation"

# Create seen file if it doesn't exist
touch "$SEEN_FILE"

# Fetch the RSS XML from n8n
RSS_XML=$(curl -s --max-time 15 "$RSS_URL")

# Parse XML, extract new articles, mark them as seen
python3 -c "
import sys, re

xml = sys.stdin.read()
seen_file = '$SEEN_FILE'

with open(seen_file, 'r') as f:
    seen = set(line.strip() for line in f if line.strip())

items = re.findall(r'<item>(.*?)</item>', xml, re.DOTALL)
new_items = []

for item in items:
    title_m = re.search(r'<title>(.*?)</title>', item, re.DOTALL)
    link_m = re.search(r'<link>(.*?)</link>', item, re.DOTALL)
    desc_m = re.search(r'<description>(.*?)</description>', item, re.DOTALL)
    date_m = re.search(r'<pubDate>(.*?)</pubDate>', item, re.DOTALL)
    author_m = re.search(r'<author>(.*?)</author>', item, re.DOTALL)
    
    title = title_m.group(1).strip() if title_m else ''
    link = link_m.group(1).strip() if link_m else ''
    desc = desc_m.group(1).strip() if desc_m else ''
    date = date_m.group(1).strip() if date_m else ''
    author = author_m.group(1).strip() if author_m else ''
    
    if link and link not in seen:
        new_items.append((title, link, desc, date, author))

if not new_items:
    sys.exit(0)

print(f'---NEW_ARTICLES_START---')
for title, link, desc, date, author in new_items:
    print(f'TITLE: {title}')
    print(f'LINK: {link}')
    print(f'DESC: {desc[:300]}')
    print(f'DATE: {date}')
    print(f'SOURCE: {author}')
    print('---')
print(f'---NEW_ARTICLES_END---')

# Mark as seen
with open(seen_file, 'a') as f:
    for _, link, _, _, _ in new_items:
        f.write(link + '\n')
" <<< "$RSS_XML"